# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

def common_pods
  #pod 'R.swift' , '4.0.0'
  pod 'R.swift' , '~> 5.0.0.alpha.2'
  pod 'XCGLogger' , '6.1.0'
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'
  pod 'RxGesture', '2.0.1'
  pod 'Action', '3.8.0'
  pod 'Alamofire', '4.7.3'
  pod 'AlamofireImage', '3.4.1'
end

workspace 'MoviesViewer.xcworkspace'

target 'MoviesViewer' do
  
  common_pods

  target 'MoviesViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
